### ISSUE TITLE
How to set environment variables?

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [ellsclytn/jellyfin-ryot-import#1]
Hi,
Noob question, but how do I set environment variables for the program?

**Comment by ellsclytn** [comment]
It's a fair question. This is going to vary a bit between OS (I'll note I only built this on Linux, so I've no idea how well it works on Windows). I'm afraid StackOverflow might give some better advice than I can for each OS ([Windows example](https://stackoverflow.com/questions/55500857/how-can-i-set-the-environment-variables-in-windows), [Linux example](https://stackoverflow.com/questions/234742/setting-environment-variables-in-linux-using-bash)).

**Comment by Gandalf-the-Blue** [comment]
Thanks. Was using Linux, and the export KEY=value commands worked!
