### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by brkr1** [ellsclytn/jellyfin-ryot-import#2]
Could you please give an example of the environment variables already set?

I'm a noobie and I'm having a hard time on doing so

**Comment by brkr1** [comment]
Nevermind. Figured it out, but when I import it in ryot it gives me this:

[frontend] GET /settings/imports-and-exports?_data=routes%2F_dashboard.settings.imports-and-exports._index 200 - - 9.825 ms
29/05/2024
15:31:07
[frontend] POST /settings/imports-and-exports?intent=deployImport&_data=routes%2F_dashboard.settings.imports-and-exports._index 200 - - 51.707 ms
29/05/2024
15:31:07
[frontend] GET /settings/imports-and-exports?_data=root 200 - - 6.153 ms
29/05/2024
15:31:07
[frontend] GET /settings/imports-and-exports?_data=routes%2F_dashboard.settings.imports-and-exports._index 200 - - 11.729 ms
29/05/2024
15:31:08
[backend] thread 'tokio-runtime-worker' panicked at apps/backend/src/importer/generic_json.rs:18:73:
29/05/2024
15:31:08
[backend] called `Result::unwrap()` on an `Err` value: Error("invalid type: map, expected a sequence", line: 1, column: 1)
29/05/2024
15:31:08
[backend] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
29/05/2024
15:31:21
[frontend] POST /settings/imports-and-exports?intent=deployImport&_data=routes%2F_dashboard.settings.imports-and-exports._index 200 - - 14.779 ms
29/05/2024
15:31:21
[frontend] GET /settings/imports-and-exports?_data=root 200 - - 3.020 ms
29/05/2024
15:31:21
[frontend] GET /settings/imports-and-exports?_data=routes%2F_dashboard.settings.imports-and-exports._index 200 - - 16.578 ms
29/05/2024
15:31:22
[backend] thread 'tokio-runtime-worker' panicked at apps/backend/src/importer/generic_json.rs:18:73:
29/05/2024
15:31:22
[backend] called `Result::unwrap()` on an `Err` value: Error("invalid type: map, expected a sequence", line: 1, column: 1)
29/05/2024
15:31:26
[frontend] GET /?_data=routes%2F_dashboard._index 200 - - 42.229 ms
29/05/2024
15:32:02
[frontend] GET /?_data=root 200 - - 4.040 ms
29/05/2024

**Comment by ellsclytn** [comment]
Hey, thanks for raising this. This should now be fixed (7d31ef3488f7f2fde3738f57bafa73951961fb41). Could you let me know how it goes?

**Comment by brkr1** [comment]
> Could you let me know how it goes?


[frontend] GET /media/list/movie?_data=routes%2F_dashboard.media.%24action.%24lot 200 - - 90.166 ms
[frontend] GET /?_data=routes%2F_dashboard._index 200 - - 51.256 ms
[frontend] GET /settings/imports-and-exports?_data=routes%2F_dashboard.settings.imports-and-exports._index 200 - - 19.516 ms
[frontend] POST /settings/imports-and-exports?intent=deployImport&_data=routes%2F_dashboard.settings.imports-and-exports._index 200 - - 82.521 ms
[frontend] GET /settings/imports-and-exports?_data=root 200 - - 5.253 ms
[frontend] GET /settings/imports-and-exports?_data=routes%2F_dashboard.settings.imports-and-exports._index 200 - - 16.964 ms
[backend] thread 'tokio-runtime-worker' panicked at apps/backend/src/importer/generic_json.rs:18:73:
[backend] called `Result::unwrap()` on an `Err` value: Error("unknown variant `show`, expected one of `AudioBook`, `Anime`, `Book`, `Podcast`, `Manga`, `Movie`, `Show`, `VideoGame`, `VisualNovel`", line: 1, column: 62)
[frontend] POST /settings/imports-and-exports?intent=deployImport&_data=routes%2F_dashboard.settings.imports-and-exports._index 200 - - 35.474 ms
[frontend] GET /settings/imports-and-exports?_data=root 200 - - 3.391 ms
[frontend] GET /settings/imports-and-exports?_data=routes%2F_dashboard.settings.imports-and-exports._index 200 - - 14.225 ms
[frontend] GET /settings/imports-and-exports 200 - - 219.899 ms
[frontend] GET /media/list/show?_data=routes%2F_dashboard.media.%24action.%24lot 200 - - 40.369 ms
[frontend] GET /media/list/movie?_data=routes%2F_dashboard.media.%24action.%24lot 200 - - 50.503 ms
[frontend] GET /?_data=routes%2F_dashboard._index 200 - - 42.201 ms

**Comment by ellsclytn** [comment]
What version of Ryot are you running?

**Comment by brkr1** [comment]
> What version of Ryot are you running?

Just updated it to latest. Just imported movies and it worked! 

Gonna try shows now. Thank you in advance!!

**Comment by ellsclytn** [comment]
Great news! I'll close this one but leave a comment if shows don't work 🙂
